#pragma config(Sensor, S1,     ir,             sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int a=0;
task main()
{
while(true)
{
	eraseDisplay();
	a=SensorValue[ir];
	nxtDisplayCenteredTextLine(3, "%d", a);
	wait1Msec(100);
}


}
