#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     L,             tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     R,             tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Controls
Joystick 1
		y1=left motor
		y2=right motor
*/


#include "JoystickDriver.c"
#define MULTI 0.5

void left(int Left){
	motor[L]=Left;
}
void right(int Right){
	motor[R]=Right;
}

task main(){
	while(true){
		getJoystickSettings(joystick);
		if(abs(joystick.joy1_y1)>10){
			left(joystick.joy1_y1*MULTI);
		}
		else{
			left(0);
		}
		if(abs(joystick.joy1_y2)>10){
			right(joystick.joy1_y2*MULTI);
		}
		else{
			right(0);
		}
	}
}
