#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          B,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     RR,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     LR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Rack1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Rack2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     G,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     empty,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     RF,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     LF,            tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    S1,                   tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    S2,                   tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SLOW 30
#define VERY SLOW 20
#define FAST 100
#define MULTI -0.5
#define SLOWMULTI -0.2
#define FASTMULTI -0.8
#include "JoystickDriver.c"
int grabberlogic=0;
void left(int S){motor[LR]=S;motor[LF]=S;}
void right(int S){motor[RF]=S;motor[RR]=S;}
void forward(int S){left(S);right(S);}
void backward(int S){left(-S);right(-S);}
void grabber(int S){motor[G]=S;}
void rackOne(int S){motor[Rack1]=S;}
void rackTwo(int S){motor[Rack2]=S;}
void flapOpen(){servo[S1]=255;}
void flapClose(){servo[S1]=128;}
void lockOpen(){servo[S2]=200;}
void lockClose(){servo[S2]=255;}
task main(){
	while(true){
		getJoystickSettings(joystick);
		/*switch(joystick.joy1_TopHat){
			case 1:
			forward(-SLOW);
			break;
			case 2:
			left(-SLOW);
			break;
			case 4:
			backward(-SLOW);
			break;
			case 6:
			right(-SLOW);
			break;
			default:*/
			if(abs(joystick.joy1_y1)>10){left(joystick.joy1_y1*MULTI);}
			else if(joystick.joy1_TopHat==1){forward(-SLOW);}
			else if(joystick.joy1_TopHat==2){left(-SLOW);}
			else if(joystick.joy1_TopHat==4){backward(-SLOW);}
			else{left(0);}
			if(abs(joystick.joy1_y2)>10){right(joystick.joy1_y2*MULTI);}
			else if(joystick.joy1_TopHat==1){forward(-SLOW);}
			else if(joystick.joy1_TopHat==4){backward(-SLOW);}
			else if(joystick.joy1_TopHat==6){right(-SLOW);}
			else{right(0);}
			if(abs(joystick.joy2_y1)>10){rackOne(joystick.joy2_y1*MULTI);}
			else if(joy1Btn(3)==1||joy2Btn(1)==1){rackOne(FAST);}
			else if(joy1Btn(4)==1||joy2Btn(2)==1){rackOne(-FAST);}
			else{rackOne(0);}
			if(abs(joystick.joy2_y2)>10){rackTwo(joystick.joy2_y2*MULTI);}
			else if(joy2Btn(3)==1){rackTwo(FAST);}
			else if(joy2Btn(4)==1){rackTwo(-FAST);}
			else{rackTwo(0);}
			if(joy1Btn(1)==1){grabberlogic=1;}
			else if(joy1Btn(2)==1){grabberlogic=0;}
			else if(joy1Btn(5)==1){grabber(-20);}
			else if(joy1Btn(6)==1){grabber(20);}
			else if(joy2Btn(5)==1){flapOpen();}
			else if(joy2Btn(6)==1){flapClose();}
			else if(joy2Btn(7)==1){lockClose();}
			else if(joy2Btn(8)==1){lockOpen();}
			else{if(grabberlogic==1){grabber(FAST);}else{grabber(0);}}
	}
}
