#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          B,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LM,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RM,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     LA,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     RA,            tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    S1,                   tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    S2,                   tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    S3,                   tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    S4,                   tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    S5,                   tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    S6,                   tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define MULTI -0.5
#define SLOW 40
#define SLOWR -40
#define ARMS 50
#define ARMF 80
void left(int speed){
	motor[LM]=speed;
}
void right(int speed){
	motor[RM]=speed;
}
void arm(int speed){
	motor[LA]=speed;
	motor[RA]=speed;
}
void grabber(int speed){
	motor[A]=speed;
	motor[B]=speed;
}
task main(){
	servoChangeRate[S1]=0;
	while(true){
		getJoystickSettings(joystick);
		if(abs(joystick.joy1_y1) > 10) {left(joystick.joy1_y1 * MULTI);}
  	else {left(0);}
  	if(abs(joystick.joy1_y2) > 10) {right(joystick.joy1_y2 * MULTI);}
 		else{right(0);}
 		//if(abs(joystick.joy2_y1) > 10) {arm(joystick.joy2_y1 * MULTI);}
 		//else{arm(0);}
 		//switch(joy1_Buttons){
 		//	case 0:
 		//	grabber(100);
 		//	break;
 		//	case 1:
 		//	grabber(-100);
 		//	break;
 		//	case 2:
 		//	grabber(100);
 		//	break;
 		//	default:
 		//	break;}
 		if(joy1Btn(1) == 1) {grabber(100);}
		else if(joy1Btn(2) == 1) {grabber(-50);}
		else {grabber (0);}
		if(joy1Btn(3) == 1) {servo[S1]=100;}
		else {}
		if(joy1Btn(4) == 1) {servo[S1]=160;}
		else {}
		//if(joy1Btn(3) == 1) {arm(ARMS);}
		//else {arm (0);}
		//if(joy1Btn(4) == 1) {arm(-ARMS);}
		//else {arm (0);}
		if(joy1Btn(5) == 1) {arm(ARMF);}
		else if(joy1Btn(6) == 1) {arm(-ARMF);}
		else {arm (0);}
	}
}
